### ISSUE TITLE
partition name

### ISSUE THREAD

**Issue by leejaymin** [kjun25/onnx_yaml-parser#6]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1924507/204967725-aa4badad-0ac6-44eb-b105-b41019220bc1.png">
위 파일들이 어떤 모델의 파티션인지 파일명을 수정해서 변경

**Comment by leejaymin** [comment]
@kjun25 답변 필요

**Comment by kjun25** [comment]
수정완료
